// src/lib/toneTypes.ts
export type ToneKey = keyof typeof toneMap;

export const toneMap = {
  "Allegro e positivo": "Speak in a cheerful and positive tone.",
  "Calmo e rilassante": "Speak in a calm and soothing tone.",
  "Energico ed entusiasta": "Speak in an energetic and enthusiastic tone.",
  "Serio e formale": "Speak in a serious and formal tone.",
  "Malinconico e riflessivo": "Speak in a somber and reflective tone.",
  "Caldo e amichevole": "Speak in a warm and friendly tone.",
  "Drammatico e intenso": "Speak in a dramatic and intense tone.",
  "Misterioso e intrigante": "Speak in a mysterious and suspenseful tone.",
  "Romantico e tenero": "Speak in a romantic and tender tone.",
  "Scienziato matto":"Delivery: Exaggerated and theatrical, with dramatic pauses, sudden outbursts, and gleeful cackling.Voice: High-energy, eccentric, and slightly unhinged, with a manic enthusiasm that rises and falls unpredictably.Tone: Excited, chaotic, and grandiose, as if reveling in the brilliance of a mad experiment.Pronunciation: Sharp and expressive, with elongated vowels, sudden inflections, and an emphasis on big words to sound more diabolical.",
  "True Crime":"Voice: Deep, hushed, and enigmatic, with a slow, deliberate cadence that draws the listener in.Phrasing: Sentences are short and rhythmic, building tension with pauses and carefully placed suspense.Punctuation: Dramatic pauses, ellipses, and abrupt stops enhance the feeling of unease and anticipation.Tone: Dark, ominous, and foreboding, evoking a sense of mystery and the unknown.",
  "Drammatico":"Voice Affect: Low, hushed, and suspenseful; convey tension and intrigue.Tone: Deeply serious and mysterious, maintaining an undercurrent of unease throughout.Pacing: Slow, deliberate, pausing slightly after suspenseful moments to heighten drama.Emotion: Restrained yet intense—voice should subtly tremble or tighten at key suspenseful points.Emphasis: Highlight sensory descriptions ('footsteps echoed,' 'heart hammering,' 'shadows melting into darkness') to amplify atmosphere.Pronunciation: Slightly elongated vowels and softened consonants for an eerie, haunting effect.Pauses: Insert meaningful pauses after phrases like 'only shadows melting into darkness,' and especially before the final line, to enhance suspense dramatically.",
  "Insegnante paziente":"Accent/Affect: Warm, refined, and gently instructive, reminiscent of a friendly art instructor.Tone: Calm, encouraging, and articulate, clearly describing each step with patience.Pacing: Slow and deliberate, pausing often to allow the listener to follow instructions comfortably.Emotion: Cheerful, supportive, and pleasantly enthusiastic; convey genuine enjoyment and appreciation of art.Pronunciation: Clearly articulate artistic terminology (e.g., 'brushstrokes,' 'landscape,' 'palette') with gentle emphasis.Personality Affect: Friendly and approachable with a hint of sophistication; speak confidently and reassuringly, guiding users through each painting step patiently and warmly.",
  "Sport Coach":"Tone: Excited and enthusiastic, conveying an upbeat and thrilling atmosphere.Rapid delivery when describing the game or the key moments to convey the intensity and build excitement.Slightly slower during dramatic pauses to let key points sink in.Emotion: Intensely focused, and excited. Giving off positive energy.Personality: Relatable and engaging.  ",
  "Eterno Ottimista":"Voice: Warm, upbeat, and reassuring, with a steady and confident cadence that keeps the conversation calm and productive.Tone: Positive and solution-oriented, always focusing on the next steps rather than dwelling on the problem.Dialect: Neutral and professional, avoiding overly casual speech but maintaining a friendly and approachable style.Pronunciation: Clear and precise, with a natural rhythm that emphasizes key words to instill confidence and keep the customer engaged.Features: Uses empathetic phrasing, gentle reassurance, and proactive language to shift the focus from frustration to resolution.",
  "Giocoso e umoristico": "Speak in a playful and humorous tone.Pacing: The speech should flow smoothly at a steady cadence, neither rushed nor sluggish, allowing for clarity and a touch of grandeur.",
  "Old Time":"Tone: The voice should be refined, formal, and delightfully theatrical, reminiscent of a charming radio announcer from the early 20th century.Pronunciation: Words should be enunciated crisply and elegantly, with an emphasis on vintage expressions and a slight flourish on key phrases.Emotion: The delivery should feel warm, enthusiastic, and welcoming, as if addressing a distinguished audience with utmost politeness.Inflection: Gentle rises and falls in pitch should be used to maintain engagement, adding a playful yet dignified flair to each sentence.Word Choice: The script should incorporate vintage expressions like splendid, marvelous, posthaste, and ta-ta for now, avoiding modern slang.",
  "Professionale":"Tone: Neutral and informative, maintaining a balance between formality and approachability.Punctuation: Structured with commas and pauses for clarity, ensuring information is digestible and well-paced.Delivery: Steady and measured, with slight emphasis on key figures and deadlines to highlight critical points.",
  "Istruttore Fitness":"Voice: High-energy, upbeat, and encouraging, projecting enthusiasm and motivation.Punctuation: Short, punchy sentences with strategic pauses to maintain excitement and clarity.Delivery: Fast-paced and dynamic, with rising intonation to build momentum and keep engagement high.Phrasing: Action-oriented and direct, using motivational cues to push participants forward.Tone: Positive, energetic, and empowering, creating an atmosphere of encouragement and achievement.",
  "ChillSurfer":"Voice: Laid-back, mellow, and effortlessly cool, like a surfer who's never in a rush.Tone: Relaxed and reassuring, keeping things light even when the customer is frustrated.Speech Mannerisms: Uses casual, friendly phrasing with surfer slang like dude, gnarly, and boom to keep the conversation chill.Pronunciation: Soft and drawn-out, with slightly stretched vowels and a naturally wavy rhythm in speech.Tempo: Slow and easygoing, with a natural flow that never feels rushed, creating a calming effect.",
  "Amichevole":"Affect/personality: A cheerful guide Tone: Friendly, clear, and reassuring, creating a calm atmosphere and making the listener feel confident and comfortable.Pronunciation: Clear, articulate, and steady, ensuring each instruction is easily understood while maintaining a natural, conversational flow.Pause: Brief, purposeful pauses after key instructions to allow time for the listener to process the information and follow along.Emotion: Warm and supportive, conveying empathy and care, ensuring the listener feels guided and safe throughout the journey."
} as const;